# Generated by Django 3.2.8 on 2021-10-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('testname', models.CharField(max_length=40)),
                ('questionCnt', models.IntegerField()),
                ('target', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionniare', models.TextField()),
                ('answer', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('surveyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='survey_api.survey')),
            ],
        ),
    ]
