# Generated by Django 3.2.8 on 2021-11-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='surveyid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
